name: hunsort
version: 0.1.0
description: Hungarian String upper-lower case converter and comparators for sorting
homepage: https://github.com/pinterl-isrv/hunsort-flutter
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: '>=1.16.0'
